# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def get_even_fibbo_sum(maximum_value):
    previous_fibbo = 1
    current_fibbo = 2
    sum_fibbo = 0

    while current_fibbo < maximum_value:
        if current_fibbo % 2 == 0:
            sum_fibbo += current_fibbo
        next_fibbo = current_fibbo + previous_fibbo
        previous_fibbo = current_fibbo
        current_fibbo = next_fibbo

    return sum_fibbo


# Answer: 4613732
